CREATE TABLE APP_USER_PERMISSION (
ID_USER NUMERIC(10) NOT NULL,
ID_PERMISSION NUMERIC(10) NOT NULL,
CONSTRAINT APP_USER_PERMISSION_PKEY PRIMARY KEY (ID_USER, ID_PERMISSION),
CONSTRAINT APP_USER_PERMISSION_USER_FK FOREIGN KEY(ID_USER) REFERENCES APP_USER(ID),
CONSTRAINT APP_USER_PERMISSION_PERMISSION_FK FOREIGN KEY(ID_PERMISSION) REFERENCES APP_PERMISSION(ID)
);