CREATE TABLE APP_USER (
ID NUMERIC(10) NOT NULL,
USER_NAME VARCHAR(255) NOT NULL UNIQUE,
FULL_NAME VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
ACCOUNT_NON_EXPIRED BOOLEAN NOT NULL,
ACCOUNT_NON_LOCKED BOOLEAN NOT NULL,
CREDENTIALS_NON_EXPIRED BOOLEAN NOT NULL,
ENABLED BOOLEAN NOT NULL,
CONSTRAINT USER_PKEY PRIMARY KEY (ID)
);