version: '3.7'
services:
  db:
    image: caiohobus/postgres-person-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: develop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      TZ: America/Sao_Paulo
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5436:5432"
    networks:
      - person-network
  person-backend:
    image: caiohobus/person-backend
    restart: always
    build: ./person-backend
    working_dir: /person-backend
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./person-backend:/person-backend
      - ~/.m2:/root/.m2
    ports:
      - "8084:8084"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - person-network
networks:
    person-network:
        driver: bridge